spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://db:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
